### ISSUE TITLE
Installation failure with npm install (windows environment: command line / gitbash)

### ISSUE THREAD

**Issue by FranDelaCasa** [scm-spain/frontend-pre-commit-rules#13]
```
francisco.delacasa@AFE0804002 MINGW64 /c/GitProjects/re-home-search (feature/doc_revision)
$ npm i
npm WARN package.json @schibstedspain/re-home-search@2.1.2 No license field.

> @schibstedspain/frontend-pre-commit-rules@6.2.2 install C:\GitProjects\re-home-search\node_modules\@schibstedspain\frontend-pre-commit-rules
> node bin/install.js

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\GitProjects\re-home-search\.git\hooks\pre-commit'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.exports.installHooks (C:\GitProjects\re-home-search\node_modules\@schibstedspain\frontend-pre-commit-rules\node_modules\git-validate\lib\utils.js:234:12)
    at Object.<anonymous> (C:\GitProjects\re-home-search\node_modules\@schibstedspain\frontend-pre-commit-rules\bin\install.js:10:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! @schibstedspain/frontend-pre-commit-rules@6.2.2 install: `node bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @schibstedspain/frontend-pre-commit-rules@6.2.2 install script 'node bin/install.js'.
npm ERR! This is most likely a problem with the @schibstedspain/frontend-pre-commit-rules package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls @schibstedspain/frontend-pre-commit-rules
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitProjects\re-home-search\npm-debug.log
```

**Comment by delacruz-dev** [comment]
Sorry, we can't reproduce this bug :(
